### ISSUE TITLE
-KOTE layer

### ISSUE THREAD

**Issue by L-CB** [archaeodav/felttegn#41] opened 2022-03-24 14:06 UTC
When running af CSV-file through FeltTegn, the layer -KOTE comes through with data in only fig, date and method. It would be very useful if the attributetable for the layer was expanded to contain X, Y and Z for the layer. The layer doesn't really make sense otherwise :-).
Lars/ArkVest

**Comment by archaeodav** [comment] 2022-04-22 11:06
Fixed in upcoming release 1.23

**Comment by archaeodav** [comment] 2022-04-22 11:07
Duplicate of #35

**Closed by archaeodav** 2022-04-22 11:07 UTC
